# gladiator.py
#	A betting game allowing the player to bet on one of two randomly generated
#	warriors. Winnings will be based on odds generated by the character's stats
#	and equipment.

from battle import Battle
from player import Player
import string
from text import printIntro,announceWarriors

def main():
	player = Player()
	printIntro()
	choice = 'yes'
	no = ['no','n']
	yes = ['yes','y','ye']
	while player.getPurse() > 0 and choice not in no:
		print "You have", player.getPurse(),"in your pouch.\n"
		battle = Battle()
		print "\nThe next battle is between %s and %s.\n" % (battle.warrior1.getName(),battle.warrior2.getName())
		announceWarriors(battle.warrior1,battle.odds1,battle.warrior2,battle.odds2)
		print "\nDo you want to bet?\n\n"
		player.getChoice(battle.warrior1,battle.warrior2)
		winner, odds = battle.battle()
		if winner == player.getPick():
			player.updatePurse("win",player.getBet(),odds)
		else:
			player.updatePurse("lose",player.getBet(),odds)

		print "\nWould you like to bet on the next battle?\n"
		while True:
			try:
				choice = string.lower(str(raw_input(">> ")))
				if choice in yes:
					break
				elif choice in no:
					choice = 'no'
					break
				else:
					print "\nPlease choose yes or no.\n"
					continue

			except ValueError:
				print "\nPlease choose yes or no.\n"
				continue

	print "\nThank you so much for playing!\n"
	if player.getPurse() > 1:
		print "\nYou leave the Colosseum with %d coins in your purse.\n" % player.getPurse()
	elif player.getPurse() == 1:
		print "\nYou leave the Colosseum with one coin, not even another to rub it against.\n"
	else:
		print "\nYou're leaving dead broke!\n"

main()
